
# Exercicios de repaso EXAME (4) FEBREIRO 2026


## Exercicio 1

A partir da listas seguintes, que conteñen o nome de varios produtos e o seu prezo:

 **produtos = ["Refresco cola", "Pizza", "Helado", "Patatas onduladas", "Salsa barbacoa"]**
 
 **prezos = [0.90, 3.29, 1.52, 1.91, 2.09]**

Crea un diccionario por comprensión chamado **inventario** no que as claves sexan os nomes dos produtos e os valores sexan o prezo correspondente ao produto. Para crear o diccionario por comprensión utiliza as dúas listas e un ZIP.

In [1]:
produtos = ["Refresco cola", "Pizza", "Helado", "Patatas onduladas", "Salsa barbacoa"]
prezos = [0.90, 3.29, 1.52, 1.91, 2.09]

inventario = { nombre:precio for nombre, precio in zip(produtos,prezos)}

print(inventario)

{'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}


## Exercicio 2

Utilizando o seguinte dicionario que é o resultado do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Mostra por pantalla o nome do produto que teña un prezo igual a 1.91 euros. Para atopalo percorre o dicionario cun **"for"** ata dar co primeiro valor que coincida co dato. Atopa unha solución alternativa obtendo as listas de claves e de valores e usando o método index() da lista de valores.


In [ ]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}




for nom, prez in inventario.items():
    if prez == 1.91:
        print(f"O produto que vale 1.91€ é {nom}")
        
claves = list(inventario.keys())
valores = list(inventario.values())

print(f"O produto que vale 1.91€ é {claves[valores.index(1.91)]}")
        


producto: Patatas onduladas
Producto: Patatas onduladas


## Exercicio 3

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Utilizando as funcións ***min()*** e ***max()*** mostra por pantalla os produtos con menor e maior prezo e o seu valor.


In [10]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}


producto_barato, precio_barato = min(inventario.items(), key=lambda x: x[1])
producto_caro, precio_caro = max(inventario.items(), key=lambda x: x[1])

print(f"Produto máis barato: {producto_barato} - {precio_barato}€")
print(f"Produto máis caro: {producto_caro} - {precio_caro}€")


producto_barato = min(inventario, key=inventario.get)
producto_caro = max(inventario, key=inventario.get)

print(f"Produto máis barato: {producto_barato} - {inventario[producto_barato]}€")
print(f"Produto máis caro: {producto_caro} - {inventario[producto_caro]}€")




# valor_min =(min(inventario.values()))
# valor_max =(max(inventario.values()))
# print(valor_min, valor_max)

# #############

# valor_min = min(inventario, key=inventario.get)
# valor_max =max (inventario, key=inventario.get)

# print(F"Productos con menor prezo da tenda : {valor_min} ")
# print(f"Producto con maior prezo do catalogo: {valor_max}")

Produto máis barato: Refresco cola - 0.9€
Produto máis caro: Pizza - 3.29€
Produto máis barato: Refresco cola - 0.9€
Produto máis caro: Pizza - 3.29€


## Exercicio 4

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Escribe por pantalla o dicionario ordenado alfabéticamente polos nomes dos produtos.

Escribe por pantalla o dicionario ordenado (de máis barato a máis caro) polo prezo dos produtos.

Escribe por pantalla o dicionario ordenado (de máis caro a máis barato) polo prezo dos produtos.


In [13]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}


print(dict(sorted(inventario.items())))
print(dict(sorted(inventario.items(), key=lambda x:x[1])) )

















# print(dict(sorted(inventario.items())))
# print(dict(sorted(inventario.items(), key=lambda item:item[1])))
# print(dict(sorted(inventario.items(), key=lambda item:item[1], reverse=True)))

# ##################
# print("-------------")
# for prod,prez in sorted(inventario.items()):
#     print(f"Produto {prod}, prezo {prez} euros")
# print("-------------")    
# for prod,prez in sorted(inventario.items(), key=lambda item:item[1]):
#     print(f"Produto {prod}, prezo {prez} euros")
# print("-------------")
# for prod,prez in sorted(inventario.items(), key=lambda item:item[1], reverse=True):
#     print(f"Produto {prod}, prezo {prez} euros")


{'Helado': 1.52, 'Patatas onduladas': 1.91, 'Pizza': 3.29, 'Refresco cola': 0.9, 'Salsa barbacoa': 2.09}
{'Refresco cola': 0.9, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09, 'Pizza': 3.29}


## Exercicio 5

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**


Crea unha tupla de nome **produtos_baratos** que conteña os nomes dos produtos cun prezo menor de 2 euros.

Crea unha tupla de nome **produtos_caros** que conteña os nomes dos produtos cun prezo igual ou superior a 2 euros.

Cra un novo dicionario de nome **inventario_nomes_simples** que conteña os produtos (e o seu prezo) que non teñan un nome composto por dúas palabras.


In [ ]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}

produtos_baratos = tuple(nom for nom,prez in inventario.items() if prez < 2)
print(produtos_baratos)

produtos_caros = tuple(nom for nom,prez in inventario.items() if prez >=2)
print(produtos_caros)

inventario_nomes_simples = {nom:prez for nom, prez in inventario.items() if len(nom.split())==1}
print(inventario_nomes_simples)


('Refresco cola', 'Helado', 'Patatas onduladas')
('Pizza', 'Salsa barbacoa')
{'Pizza': 3.29, 'Helado': 1.52}
