
# Exercicios de repaso EXAME (4) FEBREIRO 2026


## Exercicio 1

A partir da listas seguintes, que conteñen o nome de varios produtos e o seu prezo:

 **produtos = ["Refresco cola", "Pizza", "Helado", "Patatas onduladas", "Salsa barbacoa"]**
 
 **prezos = [0.90, 3.29, 1.52, 1.91, 2.09]**

Crea un diccionario por comprensión chamado **inventario** no que as claves sexan os nomes dos produtos e os valores sexan o prezo correspondente ao produto. Para crear o diccionario por comprensión utiliza as dúas listas e un ZIP.

In [4]:
produtos = ["Refresco cola", "Pizza", "Helado", "Patatas onduladas", "Salsa barbacoa"]
prezos = [0.90, 3.29, 1.52, 1.91, 2.09]

inventario = {Prod:Prez for Prod,Prez in zip(produtos,prezos)}
print(inventario)


{'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}


## Exercicio 2

Utilizando o seguinte dicionario que é o resultado do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Mostra por pantalla o nome do produto que teña un prezo igual a 1.91 euros. Para atopalo percorre o dicionario cun **"for"** ata dar co primeiro valor que coincida co dato. Atopa unha solución alternativa obtendo as listas de claves e de valores e usando o método index() da lista de valores.


In [7]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}

for clave,valor in inventario.items():
    if valor == 1.91:
        print(f"O produto que ten un prezo igual a 1.91 euros é: {clave}")
        break

produtos = list(inventario.keys())
prezos = list(inventario.values())
print(f"O produto que ten un prezo igual a 1.91 euros é: {produtos[prezos.index(1.91)]}")


O produto que ten un prezo igual a 1.91 euros é: Patatas onduladas
O produto que ten un prezo igual a 1.91 euros é: Patatas onduladas


## Exercicio 3

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Utilizando as funcións ***min()*** e ***max()*** mostra por pantalla os produtos con menor e maior prezo e o seu valor.


In [11]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}

produto_prezo_min = min(inventario,key=inventario.get)  # Compara os valores(os prezos) e devolve o clave(o produto) asociada ao menor
print(f"O produto con menor prezo é {produto_prezo_min} cun prezo igual a {inventario[produto_prezo_min]:.2f} euros")

produto_prezo_max = max(inventario,key=inventario.get)  # Compara os valores(os prezos) e devolve a clave(o produto) asociada ao maior
print(f"O produto con maior prezo é {produto_prezo_max} cun prezo igual a {inventario[produto_prezo_max]:.2f} euros")

O produto con menor prezo é Refresco cola cun prezo igual a 0.90 euros
O produto con maior prezo é Pizza cun prezo igual a 3.29 euros


## Exercicio 4

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**

Escribe por pantalla o dicionario ordenado alfabéticamente polos nomes dos produtos.

Escribe por pantalla o dicionario ordenado (de máis barato a máis caro) polo prezo dos produtos.

Escribe por pantalla o dicionario ordenado (de máis caro a máis barato) polo prezo dos produtos.


In [15]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}

for PROD, PREZ in sorted(inventario.items()):
    print(f"Produto: {PROD}  Prezo:{PREZ} euros")

print("---------")
for PROD, PREZ in sorted(inventario.items(), key=lambda item:item[1]):
    print(f"Produto: {PROD}  Prezo: {PREZ} euros")

print("---------")
for PROD, PREZ in sorted(inventario.items(), key=lambda item:item[1], reverse=True):
    print(f"Produto: {PROD}  Prezo: {PREZ} euros")


Produto: Helado  Prezo:1.52 euros
Produto: Patatas onduladas  Prezo:1.91 euros
Produto: Pizza  Prezo:3.29 euros
Produto: Refresco cola  Prezo:0.9 euros
Produto: Salsa barbacoa  Prezo:2.09 euros
---------
Produto: Refresco cola  Prezo: 0.9 euros
Produto: Helado  Prezo: 1.52 euros
Produto: Patatas onduladas  Prezo: 1.91 euros
Produto: Salsa barbacoa  Prezo: 2.09 euros
Produto: Pizza  Prezo: 3.29 euros
---------
Produto: Pizza  Prezo: 3.29 euros
Produto: Salsa barbacoa  Prezo: 2.09 euros
Produto: Patatas onduladas  Prezo: 1.91 euros
Produto: Helado  Prezo: 1.52 euros
Produto: Refresco cola  Prezo: 0.9 euros


## Exercicio 5

Utilizando o mesmo dicionario do exercicio anterior:

**inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}**


Crea unha tupla de nome **produtos_baratos** que conteña os nomes dos produtos cun prezo menor de 2 euros.

Crea unha tupla de nome **produtos_caros** que conteña os nomes dos produtos cun prezo igual ou superior a 2 euros.

Cra un novo dicionario de nome **inventario_nomes_simples** que conteña os produtos (e o seu prezo) que non teñan un nome composto por dúas palabras.


In [23]:
inventario = {'Refresco cola': 0.9, 'Pizza': 3.29, 'Helado': 1.52, 'Patatas onduladas': 1.91, 'Salsa barbacoa': 2.09}

produtos_baratos = tuple([PROD for PROD,PREZ in inventario.items() if PREZ<2])
print(produtos_baratos)

produtos_caros = tuple((PROD for PROD,PREZ in inventario.items() if PREZ>=2))
print(produtos_caros)

inventario_nomes_simples = {Prod:Prez for Prod,Prez in inventario.items() if ' ' not in Prod}
print(inventario_nomes_simples)

('Refresco cola', 'Helado', 'Patatas onduladas')
('Pizza', 'Salsa barbacoa')
{'Pizza': 3.29, 'Helado': 1.52}
